/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.FacultyJFrame;

import info5100.university.example.College.College;
import info5100.university.example.Role.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class AddCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCourseJPanel
     */
    
    private College college;
    private UserAccount userAccount;
    
    private DefaultTableModel courseTableModel;
    
    public AddCourseJPanel(College college, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        
        this.college = college;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTopic = new javax.swing.JTextField();
        txtRegion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        txtCredit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Course Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 110, 30));

        jLabel2.setText("Topic:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 110, 30));

        jLabel3.setText("Region:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Language:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        add(txtTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 110, 30));
        add(txtRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, 30));

        jLabel5.setText("Credit:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel6.setText("Price:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 20));
        add(txtLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, 30));
        add(txtCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, 30));

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Topic", "Region", "Language", "Credit", "Price"
            }
        ));
        jScrollPane1.setViewportView(courseTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 530, 240));

        createBtn.setText("CREATE");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 120, 30));

        deleteBtn.setText("DELETE");
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:

        //get course information
        String userName = fieldusername.getText();
        String pass = fieldPassword.getText();
        String name = fieldname.getText();
        int exp = Integer.valueOf(fieldexperience.getText());
        String role = (String) designationCombo.getSelectedItem();
        String branch = (String) branchCombo.getSelectedItem();

        //check user account unique
        if(!uad.checkUserNameUnique(userName)) {
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
        }
        //create user account and employee profile
        else {
            if (role.equals("librarian")){
                UserAccount user = uad.createUserAccount(userName, pass, new LibrarianRole());
                Library lib = this.app.getBranchDirectory().findBranch(branch).getLibrary();
                lib.getEmployeeDirectory().createEmployee(exp, role, name,user.getAccountid(), lib);

            } else if(role.equals("branch manager")){
                UserAccount user = uad.createUserAccount(userName, pass, new BranchManagerRole());
                Library lib = this.app.getBranchDirectory().findBranch(branch).getLibrary();
                lib.getEmployeeDirectory().createEmployee(exp, role, name,user.getAccountid(), lib);

            }
            populateCourseTable();
        }
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable courseTable;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtTopic;
    // End of variables declaration//GEN-END:variables
}
