/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.FacultyJFrame;

import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Platform.Platform;
import info5100.university.example.Role.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author Ma2017
 */
public class ProfessorAnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorAnalyticsJPanel
     */    
    private Platform pf;
    private UserAccount ua; 
    private FacultyProfile fp;
    
    public ProfessorAnalyticsJPanel() {
        initComponents();
        this.setVisible(true);
    }
    public ProfessorAnalyticsJPanel(Platform pf, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        this.pf = pf;
        this.ua = userAccount;
        this.fp= this.pf.getFacultydirectory().findProfessorById(ua.getAccountId());
        
        jLabel2.setText(String.valueOf(this.fp.getEnrolledListForAllTerm().size()));
        fee.setText(String.valueOf(0.15 * this.fp.getTuitionCollected()));
    }

    /**
     * This method is called from within the constructor t】【o initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fee1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Number of students：");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel1.setText("（15% of your total revenue)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setText("0");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 90, -1));

        fee.setText("0");
        add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setText("My Revenue from course：");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel6.setText("hidden due to unsubscribe");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        subButton.setText("Subscribe to platform");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });
        add(subButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Subscription Fee need to pay:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton2.setText("View my revenue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, 20));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel7.setText("Subscription Fee already paid:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        fee1.setText("0");
        add(fee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
      
       
        this.pf.addCollectionFee(0.15*this.fp.getTuitionCollected());//add revenue to platform
        this.fp.setIsSubscript(true);
        
        JOptionPane.showMessageDialog(null, "Successfully Pay!");
        fee1.setText(String.valueOf(0.15 * this.fp.getTuitionCollected()));
    }//GEN-LAST:event_subButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!this.fp.isIsSubscript()){
            JOptionPane.showMessageDialog(null, "Cannot view because you did not subscript");
        }else{
            jLabel6.setText(String.valueOf(this.fp.getTuitionCollected()));
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fee;
    private javax.swing.JLabel fee1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton subButton;
    // End of variables declaration//GEN-END:variables
}
