/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.FacultyJFrame;

import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Platform.Platform;
import info5100.university.example.Role.UserAccount;
import javax.swing.JOptionPane;

/**
 *
 * @author Ma2017
 */
public class ProfessorAnalyticsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorAnalyticsJPanel
     */    
    private Platform pf;
    private UserAccount ua; 
    private FacultyProfile fp;
    
    public ProfessorAnalyticsJPanel() {
        initComponents();
        this.setVisible(true);
    }
    public ProfessorAnalyticsJPanel(Platform pf, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        this.pf = pf;
        this.ua = userAccount;
        this.fp= this.pf.getFacultydirectory().findProfessorById(ua.getAccountId());
        
        jLabel6.setText(String.valueOf(this.fp.getTuitionCollected()));
        jLabel2.setText(String.valueOf(this.fp.getEnrolledListForAllTermOnly().size()));
        fee.setText(String.valueOf(0.15 * this.fp.getTuitionCollected()));
    }

    /**
     * This method is called from within the constructor t】【o initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Number of students：");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel1.setText("（15% of your total revenue)");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel2.setText("0");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, -1));

        fee.setText("0");
        add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 30, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setText("Total Revenue：");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setText("0");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jButton1.setText("Subscribe to platform");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Subscription Fee need to pay：");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       
        this.pf.addCollectionFee(0.15*this.fp.getTuitionCollected());//add revenue to platform
        
        JOptionPane.showMessageDialog(null, "Successfully Pay!");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
