/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.FacultyJFrame;

import info5100.university.example.Authority.AuthorityProfile;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.CourseCatalog.CourseLoad;
import info5100.university.example.CourseCatalog.CourseOffer;
import info5100.university.example.CourseCatalog.CourseSchedule;
import info5100.university.example.CourseCatalog.Seat;
import info5100.university.example.CourseCatalog.SeatAssignment;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Platform.Platform;
import info5100.university.example.Role.UserAccount;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ma2017
 */
public class StudentMgtJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentMgtJPanel
     */
    private Platform platform;
    private UserAccount ua;
    private FacultyProfile professor;
    private DefaultTableModel studentTableModel;
    private String selectedTerm;

    public StudentMgtJPanel() {
        initComponents();
        this.setVisible(true);
    }

    public StudentMgtJPanel(Platform platform, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.platform = platform;
        this.ua = useraccount;
        this.professor = this.platform.getFacultydirectory().findProfessorById(ua.getAccountId());
        this.studentTableModel = (DefaultTableModel) studentTable.getModel();
        this.selectedTerm = (String) jComboBox2.getSelectedItem();

//        rating.setText(String.valueOf(this.professor.getReputation()));
        populateRateOfPro();
        populateStudentTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        gradeBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Term");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student ID", "Grade Status", "CourseId", "Term"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 470, 340));

        gradeBtn.setText("grade");
        gradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeBtnActionPerformed(evt);
            }
        });
        add(gradeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel3.setText("My rating from students:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 20));

        rating.setText("0");
        add(rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "F" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 160, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022Fall", "2023Spring", "2023Summer" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void gradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = studentTable.getSelectedRow();
        StudentProfile student = (StudentProfile) studentTable.getValueAt(selectedRow, 0);

        String courseName = this.selectedCourse.getName();

        if (selectedRow >= 0) {
            for (Map.Entry<String, CourseLoad> courseLoads : student.getTranscript().getCourseloadlist().entrySet()) {
                CourseLoad cl = courseLoads.getValue();
                for (SeatAssignment sa : cl.getSeatassignments()) {
                    if (sa.getSeat().getCourseoffer().getCourse().getName().equals(courseName)) {
                        float g;
                        if (jComboBox1.getSelectedItem().equals("A")) {
                            g = 4.0f;
                        } else if (jComboBox1.getSelectedItem().equals("B")) {
                            g = 3.0f;
                        } else if (jComboBox1.getSelectedItem().equals("C")) {
                            g = 2.0f;
                        } else {
                            g = 0.0f;
                        }

                        sa.setGrade(g);
                        break;
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a student");
        }

        populateStudentTable();
    }//GEN-LAST:event_gradeBtnActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        populateStudentTable();
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    public void populateStudentTable() {
        if (this.professor.getEnrolledListForAllTerm().size() > 0) {
            studentTableModel.setRowCount(0);
            String term = (String) jComboBox2.getSelectedItem();

            CourseSchedule cs = this.professor.getAllSchedules().get(term);

            ArrayList<CourseOffer> offers = cs.getSchedule();

            for (CourseOffer co : offers) {
//                    ArrayList<Student> enrolledStudentList = co.getEnrolledStudentList();
                for (Seat s : co.getSeatlist()) {
                    if (s.isOccupied() == true) {

                        Object[] row = new Object[5];

                        row[0] = s.getSeatassignment().getCourseload().getStudent().getPerson().getPersonId();
                        row[1] = s.getSeatassignment().getCourseload().getStudent().getPerson().getNameOfPerson();
                        row[2] = s.getSeatassignment().getGrade();
                        row[3] = s.getCourseoffer().getCourse().getCourseId();
                        row[4] = s.getCourseoffer().getCourse().getTerm();

                        studentTableModel.addRow(row);
                    }
                }
            }
        }
    }

//    public void populateStudentsForCourse() {
//        if (this.professor.getEnrolledListForAllTerm().size() > 0) {
//            studentTableModel.setRowCount(0);
//
//            for (Map.Entry<String, CourseSchedule> termSchedule : this.professor.getAllSchedules().entrySet()) {
//                CourseSchedule cs = termSchedule.getValue();
//                ArrayList<CourseOffer> offers = cs.getSchedule();
//
//                for (CourseOffer co : offers) {
//                    //only show students enrolled in the selected course
//                    if (co.getCourse().getName().equals(fieldCourseName.getText())) {
//                        for (Seat s : co.getSeatlist()) {
//                            if (s.isOccupied() == true) {
//
//                                Object[] row = new Object[3];
//
//                                row[0] = s.getSeatassignment().getCourseload().getStudent().getPerson().getPersonId();
//                                row[1] = s.getSeatassignment().getCourseload().getStudent().getPerson().getNameOfPerson();
//                                row[2] = s.getSeatassignment().getGrade();
//
//                                studentTableModel.addRow(row);
//                            }
//                        }
//                    }
//
//                }
//            }
//
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradeBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rating;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables

    private void populateRateOfPro() {
        FacultyProfile fp = this.platform.getFacultydirectory().findProfessorById(this.ua.getAccountId());
        rating.setText(String.valueOf(fp.getReputation()));
    }
}
