/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.AdminWorkArea;

import info5100.university.example.Authority.AuthorityProfile;
import info5100.university.example.CourseCatalog.Course;
import info5100.university.example.Persona.Faculty.FacultyProfile;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Platform.Platform;
import info5100.university.example.Role.UserAccount;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ma2017
 */
public class ShowJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowJPanel
     */
    private Platform pf;
    private UserAccount ua;
    DefaultTableModel profTableModel;
    DefaultTableModel authorityTableModel;
    DefaultTableModel stuTableModel;
    DefaultTableModel courseTableModel;

    public ShowJPanel() {
        initComponents();
    }

    public ShowJPanel(Platform platform, UserAccount userAccount) {
        initComponents();
        this.pf = platform;
        this.ua = userAccount;
        this.profTableModel = (DefaultTableModel) profTable.getModel();
        this.authorityTableModel = (DefaultTableModel) authorityTable.getModel();
        this.stuTableModel = (DefaultTableModel) stuTable.getModel();
        this.courseTableModel = (DefaultTableModel) courseTable.getModel();

        populateProfTotalRevenue();

        populateAllStudent();

        populateAllCourse();

        populateAllAuthority();
        jLabel2.setText(String.valueOf(this.pf.getCollectionFee()));
    }

    public void populateAllStudent() {
        stuTableModel.setRowCount(0);
        for (StudentProfile sp : this.pf.getStudentdirectory().getStudentlist()) {
            Object[] row = new Object[3];

            row[0] = sp;
            row[1] = sp.getPerson().getPersonId();
            row[2] = sp.getTranscript().getGraduateStatus();

            stuTableModel.addRow(row);
        }
    }

    public void populateAllAuthority() {
        authorityTableModel.setRowCount(0);
        for (AuthorityProfile ap : this.pf.getAuthoritydirectory().getAuthoritylist()) {
            Object[] row = new Object[2];

            row[0] = ap.getPerson().getPersonId();
            row[1] = ap.getPerson().getNameOfPerson();

            authorityTableModel.addRow(row);
        }
    }

    public void populateAllCourse() {
        courseTableModel.setRowCount(0);
        for (FacultyProfile fp : this.pf.getFacultydirectory().getProfessors()) {
            for (Course c : fp.getCourseCatalog().getCourses()) {
            Object[] row = new Object[8];
            row[0] = c;
            row[1] = c.getName();
            row[2] = c.getLanguage();
            row[3] = c.getTopic();

            row[4] = c.getRegion();
            row[5] = c.getCredit();
            row[6] = c.getPrice();
            row[7] = this.pf.getFacultydirectory().findProfessorByName(c.getProfname()).getPerson().getNameOfPerson();

            courseTableModel.addRow(row);
            }
        }
    }

    public void populateProfTotalRevenue() {
        ArrayList<FacultyProfile> facultyList = this.pf.getFacultydirectory().getProfessors();
        profTableModel.setRowCount(0);
        for (FacultyProfile fp : facultyList) {
            Object[] row = new Object[3];

            row[0] = fp.getPerson().getPersonId();
            row[1] = fp.getPerson().getNameOfPerson();
            row[2] = fp.getTuitionCollected();

            profTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        profTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        authorityTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prof Name", "Prof ID", "Prof Revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(profTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 160));

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseName", "CourseNum", "language", "topic", "region", "credit", "price", "professor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(courseTable);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 750, 160));

        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stu Name", "Stu ID", "IsGradute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 230, 160));

        authorityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AuthorityId", "AuthorityName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(authorityTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 220, 160));

        jLabel1.setText("Total Revenue of the platform:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, -1));

        jLabel2.setText("defalut revenue");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable authorityTable;
    private javax.swing.JTable courseTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable profTable;
    private javax.swing.JTable stuTable;
    // End of variables declaration//GEN-END:variables
}
