/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.AdminWorkArea;

import info5100.university.example.College.College;
import info5100.university.example.Role.UserAccount;

/**
 *
 * @author Ma2017
 */
public class ShowJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowJPanel
     */
  
    private College college;
    private UserAccount userAccount; 
    
    public ShowJPanel() {
        initComponents();
    }
    
    public ShowJPanel(College college, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableS = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableP = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableP1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableP2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stu Name", "Stu ID", "IsGradute"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableS);
        if (jTableS.getColumnModel().getColumnCount() > 0) {
            jTableS.getColumnModel().getColumn(1).setHeaderValue("CourseNum");
            jTableS.getColumnModel().getColumn(2).setHeaderValue("language");
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 261, 160));

        jTableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AuthorityName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableP);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 261, 160));

        jTableP1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prof Name", "Prof ID", "Prof Revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableP1);
        if (jTableP1.getColumnModel().getColumnCount() > 0) {
            jTableP1.getColumnModel().getColumn(1).setHeaderValue("CourseNum");
            jTableP1.getColumnModel().getColumn(2).setHeaderValue("language");
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 261, 160));

        jTableP2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CourseName", "CourseNum", "language"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableP2);
        if (jTableP2.getColumnModel().getColumnCount() > 0) {
            jTableP2.getColumnModel().getColumn(1).setHeaderValue("CourseNum");
            jTableP2.getColumnModel().getColumn(2).setHeaderValue("language");
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 261, 160));

        jLabel1.setText("Total Revenue of the platform:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, -1));

        jLabel2.setText("defalut revenue");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableP;
    private javax.swing.JTable jTableP1;
    private javax.swing.JTable jTableP2;
    private javax.swing.JTable jTableS;
    // End of variables declaration//GEN-END:variables
}
