/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI.StudentWorkArea;

import info5100.university.example.College.College;
import info5100.university.example.Role.UserAccount;

/**
 *
 * @author Ma2017
 */
public class TranscriptJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranscriptJPanel
     */
        private College college;
    private UserAccount userAccount; 
    
    
    public TranscriptJPanel() {
        initComponents();
        this.setVisible(true);
    }
    
    public TranscriptJPanel(College college, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rateBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        requestBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Registed Plan");

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "CourseNumber", "CourseNumber", "Professor", "Grade", "RateOfPro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 600, 210));

        rateBtn.setText("Rating");
        add(rateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Not ready to gradue!");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 200, 20));

        RateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateFieldActionPerformed(evt);
            }
        });
        add(RateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 170, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Choose the third authority to evaluate your request:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 380, 20));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel5.setText("Graduate request status:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 20));

        requestBtn.setText("Request to graduate");
        add(requestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 200, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 180, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel6.setText("Rating professor you selected:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void RateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RateFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RateField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton rateBtn;
    private javax.swing.JButton requestBtn;
    // End of variables declaration//GEN-END:variables
}
