/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package info5100.university.example.UI;

import info5100.university.example.College.College;
import info5100.university.example.Role.UserAccount;
import info5100.university.example.Role.UserAccountDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author alilovepeach
 */
public class SignInJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignInJPanel
     */
    private College college;
    private UserAccount userAccount;
    private UserAccountDirectory uad;
    public SignInJPanel() {
        initComponents();
           
    }
    
    
    public SignInJPanel(College college, UserAccount userAccount) {
        initComponents();
        this.college = college;
        this.uad = college.findDepartment("Information System").getUad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JTextField();
        fieldUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Username");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
        add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 168, 30));
        add(fieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 168, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Professor As A Service Cloud");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 360, 40));

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        if(this.uad.authenticateStudentUser(fieldUserName.getText(), fieldPassword.getText()) != null) {
            UserAccount studentUser = this.uad.authenticateStudentUser(fieldUserName.getText(), fieldPassword.getText());
            studentUser.getRole().createWorkArea(this.college, studentUser);
            this.setVisible(false);
        }else if(this.uad.authenticateFacultyUser(fieldUserName.getText(), fieldPassword.getText()) != null ){
            UserAccount facultyUser = this.uad.authenticateFacultyUser(fieldUserName.getText(), fieldPassword.getText());
            facultyUser.getRole().createWorkArea(this.college, facultyUser);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
        }
    }//GEN-LAST:event_btnSignInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
